apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins
spec:
  serviceAccount: jenkins-admin
  containers:
  - name: jnlp
    image: 10.1.161.30:10014/library/jnlp-agent-maven@sha256:fc9680ceeb6eb1213e8e14e564ea574cde207a69813c49275365548af1cdb109
    imagePullPolicy: IfNotPresent
    env:
      - name: TZ
        value: Asia/Shanghai
    volumeMounts:
      - name: docker-sh
        mountPath: /usr/bin/docker
      - name: docker-sock
        mountPath: /var/run/docker.sock
      - name: maven-cache
        mountPath: /root/.m2
  volumes:
    - name: docker-sh
      hostPath:
        path: /usr/bin/docker
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: maven-cache
      nfs:
        server: 10.1.161.30
        path: /nfs/maven/repository